### ISSUE TITLE
incorrect implementation of a password salt

### ISSUE THREAD

**Issue by ghost** [ashnur/random-token#1]
check out this: https://crackstation.net/hashing-security.htm#salt

to see how to properly implement a salted password generator. right now you're using the "salt" as the list of characters that can be in the generated token.

**Comment by ashnur** [comment]
Hi, thanks for that link. You are right, and I am well aware of the misused terminology, it just happens that I am terrible at naming things. I couldn't come up with a better name for "the list of characters that can be in the generated token" :). 

And to be clear, I would never use this lib for anything security related, it's just a simple way to have a random string in a convenient matter.

**Comment by ghost** [comment]
cool! thanks for replying 😄
