### ISSUE TITLE
how to `import` this package?

### ISSUE THREAD

**Issue by Usama-Tahir** [ashnur/random-token#2]
right now, only 
```const randomToken = require('random-token');```
 syntax is supported I believe. But how can we use it in `import` like way?

**Comment by ashnur** [comment]
That's a very good question :) 

ES modules (aka. export/import) is still only accessible under a --experimental-modules flag in nodejs.  As you can see the repository is ~6 years old. At the time export/import was not something I had to consider seriously. 

Even today, most people use babel to support export/import and a bundler to support require. 

So to answer your question, it depends where you want to use it. 

On the other hand, the whole module is quite a small code

```
  // return a number between 0 and max-1
    function r(max){ return Math.floor(Math.random()*max) }

    function generate(salt, size){
        var key = ''
        var sl = salt.length
        while ( size -- ) {
            var rnd = r(sl)
            key += salt[rnd]
        }
        return key
    }

    var rndtok = function(salt, size){
        return isNaN(size) ? undefined :
               size < 1    ? undefined : generate(salt, size)

    }

    rndtok.gen = createGenerator

    function createGenerator(salt){
        salt = typeof salt  == 'string' && salt.length > 0 ? salt :  'abcdefghijklmnopqrstuvwxzy0123456789'
        var temp = rndtok.bind(rndtok, salt)
        temp.salt = function(){ return salt }
        temp.create = createGenerator
        temp.gen = createGenerator
        return temp
    }

    module.exports = createGenerator()

```

You can copy just that and then no need to import.

**Comment by Usama-Tahir** [comment]
thanks. I will use this code for now and will try to make a PR supporting `import` syntax.

**Comment by Usama-Tahir** [comment]
`import * as  randomToken from 'random-token'` also works in typescript

**Comment by ashnur** [comment]
Thanks, good to know.
